apiVersion: v2
appVersion: 11.2.1
dependencies:
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 8.5.2
description: A Helm chart for Kubernetes
name: grafana
version: 8.5.2
